1.) Give a brief explanation of what each of the three most important python libraries does - a.) pandas b.) numpy c.) matplotlib

In [ ]:
pandas: is a library based on numpy, c and other languages. With pandas we can work with the data frames. 
pe, when downloaded the csv of titanic and carried on an analysis of the file.
Numpy: is allow us to work with list, array, etc. We can create random sample from an already created sample or a distribution 
like a normal distribution, binomial, poisson...
matplot.lib: we use this library to plot data on a graph. For expamle, an histogram or point. 

In [1]:
import matplotlib as plt

2.) Write a python list comprehension that will return every element in a list, L, cubed

In [2]:
import numpy as np
import pandas as pd

In [22]:
l=np.random.random_integers(0,10,10)
l

C:\Users\Thinkpad-07\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: This function is deprecated. Please call randint(0, 10 + 1) instead
  """Entry point for launching an IPython kernel.


array([7, 5, 6, 1, 8, 3, 5, 3, 6, 0])

In [23]:
for i in range(0,10):
    l[i]=l[i]**3
    print(l)


[343   5   6   1   8   3   5   3   6   0]
[343 125   6   1   8   3   5   3   6   0]
[343 125 216   1   8   3   5   3   6   0]
[343 125 216   1   8   3   5   3   6   0]
[343 125 216   1 512   3   5   3   6   0]
[343 125 216   1 512  27   5   3   6   0]
[343 125 216   1 512  27 125   3   6   0]
[343 125 216   1 512  27 125  27   6   0]
[343 125 216   1 512  27 125  27 216   0]
[343 125 216   1 512  27 125  27 216   0]


3.) Write a function in python that will return the $R^2$ value for a given $y$ and $\hat{y}$

from sklearn.linear_model import LinearRegression
lm=LinearRegression()
lm.fit(X, y)
y_hat=lm.predict(X)
lm.score(X,y)

4.) Write the code that will give total number of NaN values in each column in a pandas dataframe, df.

In [ ]:
# import pandas library

df.isna().sum()

5.) If a model has high variance, then:
a.) is it likely underfit or overfit?
b.) is it likely to have high bias or low bias?
c.) have a higher test RMSE or a lower test RMSE, compared to the training set RMSE
d.) have a higher test $R^2$ or a lower test $R^2$, compared to the training set $R^2$

a.) underfit.The model may not represent good the distribution of the values

b.) hight vias. The difference between y and y_hat values is big

c.) this depends on the split selected. But as it has a hight variance, it's more likely to have worse test RMSE

d.) i model with high variance is not a good model. Thus, is not a good representation of future data. 
 so we may ave wose R2_test values

6.) What is the two step process for "importing" packages in R(the two commands)?  Write the code below

In [ ]:
# 1. install.pakages('name of package'): istall.packages('dplyr')
# 2.import library: library(dplyr)

7.) In the equation $\hat{y} = w_0 + w_1x_1 + w_2x_2$ how do we interpret the coefficient $w_1$?

8.) What is the "cost" or "loss" function associated with linear regression?

9.) Explain why we would want to split our data into a training and test set

In [24]:
# this way  we can evaluate the model created with the train data with the test value data. Considering this last
# as future data which our model could face in the future

10.) In R, what is the function we use to make a linear regression?

In [ ]:
# lm(x,y)

11.) Name and briefly describe one cross-validation technique

In [ ]:
from teain_test_split, carry on different split based on k-fold of the same sample and give different
values of R2 with the method cross_val_score. 
we normally get the mean of thore r2 values

Bonus: Give the formula of the normal equation